CREATE TABLE `Log` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LOG_CLASS` text DEFAULT NULL,
  `LOG_ERROR` text DEFAULT NULL,
  `LOG_CREATEDAT` date,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8